<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/style.css">
    <title>Consoles de jeu</title>
  </head>
  <body class="body--index">
    <main>
      <section class="bloc">
        <article class="sony--bloc">
          <h1 class="title--sony"><a href="php/sony-index.php" class="link--sony decoration">Sony</a></h1>
        </article>
        <article class="microsoft--bloc">
          <h1 class="title--microsoft"><a href="php/microsoft-index.php" class="link--microsoft decoration">Microsoft</a></h1>
        </article>
      </section>
    </main>
    <footer>Ce site a été fait par Selmene Soualmi, apprenti en formation de développeur web à  <a href="https://3wa.fr/" class="link--3wa decoration">Cloud Campus</a></footer>
  </body>
  </html>
