<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../css/style_2.css">
    <title><?= $title ?></title>
  </head>
  <body class="body--microsoftindex">
    <section class="bloc--microsoftindex">
      <article class="bloc--microsoft bloc--present">
        <h1 class="title--present"><a href="https://fr.wikipedia.org/wiki/Sony" class="link--present decoration">Présentation</a></h1>
        </article>
        <article class="bloc--microsoft bloc--consoles_2">
          <h1 class="title--consoles"><a href="consoles_microsoft-index.php" class="decoration link--consoles">Consoles</a></h1>
        </article>
      </section>
    </body>
    </html>
