<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../css/style.css">
    <title><?= $title ?></title>
  </head>
  <body class="body--consoles">
    <main>
      <section>

        <article class="item--consoles title--ps1">
          <h1><a href="playstation1.php" class="decoration link--ps1">Playstation 1</a></h1>
        </article>
        <article class="item--consoles title--ps2">
          <h1><a href="playstation2.php" class="decoration link--ps2">Playstation 2</a></h1>
        </article>
        <article class="item--consoles title--ps3">
          <h1><a href="playstation3.php" class="decoration link--ps3">Playstation 3</a></h1>
        </article>
        <article class="item--consoles title--ps4">
          <h1><a href="playstation4.php" class="decoration link--ps4">Playstation 4</a></h1>
        </article>
          <article class="item--consoles title--ps5">
            <h1><a href="playstation5.php" class="decoration link--ps5">Playstation 5</a></h1>
          </article>
  </section>
  </main>

  </body>
</html>
