<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../css/play.css">
    <title><?= $title ?></title>
  </head>
  <body>
    <header class="entete">
      <nav>
        <ul class="list--links">
          <li><a href="#composants">Composants</a></li>
          <li><a href="#jeux">Jeux</a></li>
          <li><a href="#histoire">Histoire</a></li>
        </ul>
      </nav>
    </header>
    <main>
      <p>La PlayStation 5 (abrégée officiellement <span class="maj">ps</span>5) est la prochaine console de jeux vidéo de Sony Interactive Entertainment en développement depuis 2015, annoncée le 16 avril 2019 et dont la sortie a été confirmée pour les fêtes de fin d'année 2020.

Elle succède à la PlayStation 4 et se placera en concurrence avec la probable future Xbox Series X et avec la Nintendo Switch.</p>
<p>On peut aussi ajouter que cette page sera beaucoup plus courte que les autres du fait que la console vient d'être annoncée que très récemment de ce fait les informations concernant celle-ci ne sont pas encore toutes sorties. Enfin, il risque probablement d'avoir de fausses informations(à cause des fakes news) et si c'est le cas je m'en excuse d'avance.</p>
      <section id="composants">
        <h1 class="title">Composants de la PlayStation 5</h1>
        <article class="item--comp">
          <h1 class="title">Architecture de la console:</h1>
          <p>La console disposera des spécificités techniques suivantes :
          <ul>
            <li>Processeur de type <span class="maj">apu</span> de chez <span class="maj">amd</span> utilisant la micro-architecture « Zen 2 » 8 cœurs gravé en 7nm avec un <span class="maj">gpu</span> de famille « Navi » </li>
            <li>Audio 3D</li>
            <li>Disque <span class="maj">ssd</span></li>
            <li>Lecteur disque Blu-ray compatible avec les Blu-ray Ultra <span class="maj">hd</span> de 100 Go</li>
            <li>Support du ray tracing matériel</li>
          </ul>
        </p>
        </article>
        <article class="item--comp">
          <p>Elle devrait également proposer les fonctionnalités suivantes :
            <ul>
              <li>Support physique pour les jeux ;</li>
              <li>Rétro-compatibilité avec les jeux PlayStation 4;</li>
              <li>Compatibilité PlayStation <span class="maj">vr</span>;</li>
              <li>Possibilité d'effectuer des installations partielles des jeux;</li>
              <li>Résolution graphique pouvant aller jusqu'à la 8K.</li>
            </ul>
            En marge du partenariat du constructeur avec l'alliance Playing for the Planet, la consommation électrique de la console en veille sera moindre que celle de la PlayStation 4 (0,5 W)
          </p>
        </article>
      </section>
      <section id="jeux">
        <h1 class="title">Jeux déjà annoncés pour la PlayStation 5</h1>
        <p>Le 23 mars 2019, l'éditeur Allemand Deadalic annonce le développement du jeu <span class="italic">The Lord of the Rings - Gollum</span> et table pour une sortie en 2021 sur PC et consoles. Alors que les consoles de nouvelle génération sont envisageables pour une telle date de sortie, le magazine <span class="maj">edge</span> confirme au travers d'une preview, dans son numéro 341, que <span class="italic">The Lord of the Rings - Gollum</span> est un titre next-gen (PlayStation 5 et Xbox Series X).</p>
        <p>Le 8 octobre 2019, Marco Thrush, <span class="maj">pdg</span> du studio Bluepoint Games, annonce le développement d'un jeu <span class="maj">aaa</span> sur PlayStation 5.

        Ubisoft annonce fin octobre 2019 que les jeux <span class="italic">Watch Dogs Legion, Tom Clancy's Rainbow Six: Quarantine et Gods & Monsters</span> seront des jeux cross-gen.

        Lors de l'édition 2019 des Game Awards, <span class="italic">Godfall</span> est annoncé en tant qu'exclusivité console.

        Le 11 février 2020, Square Enix annonce que <span class="italic">Outriders</span> sortira également sur les consoles nouvelle génération, dont la <span class="maj">PS</span>5.</p>
      </section>
      <section id="histoire">
        <h1 class="title">Histoire de la PlayStation 5</h1>
        <p>La future PlayStation a été annoncée lors d'une entrevue accordé par Mark Cerny, concepteur de la <span class="maj">ps</span>4 et de la prochaine console, pour le site Wired en Californie le 16 avril 2019. Il dévoile des futures fonctionnalités de cette dernière.

          Quelques jours plus tard, Sony confirme aux journalistes et aux actionnaires que la sortie de la console n'est pas prévue pour les douze prochains mois, ce qui exclu toute hypothèse d'une sortie début 2020.

          Le nom de la console a été officialisé le 8 octobre 2019 et suit la dénomination habituelle en utilisant PlayStation 5 comme nom. La console comporte des évolutions notables comme la prise en charge du ray tracing (basée sur une variante personnalisée de la famille Navi d’<span class="maj">amd</span> Radeon), un processeur octo-core amélioré (puce <span class="maj">amd</span> basée sur la microarchitecture Zen 2), une puce audio plus performante pour une gestion de l'audio en trois dimensions et d'un <span class="maj">ssd</span> « très rapide » en lieu et place d'un disque dur pour diminuer considérablement les temps de chargement. La rétro-compatibilité avec les jeux <span class="maj">ps</span>4 et la compatibilité avec la réalité virtuelle ont été annoncées, pour cette dernière via la prise en charge du PlayStation <span class="maj">VR</span>.</p>
          <p>Le 8 octobre 2019, Jim Ryan a annoncé que la PlayStation 5 serait disponible à temps pour les fêtes de fin d'année 2020. À cette occasion, il confirme officiellement la dénomination PlayStation 5 de la console, ainsi que tous les détails techniques dévoilés jusque là, comme le support matériel du ray tracing ou encore la manette de jeu à résistance haptique techniquement proche de la DualShock 4.

            Le 7 janvier 2020, Jim Ryan dévoile le logo de la console lors de la conférence du Consumer Electronic Show du constructeur.

            Le 4 février 2020, la page officielle de la PlayStation 5 est mise en ligne.

            Le 14 février 2020, le journal Bloomberg évoque une incapacité pour le constructeur Sony de fixer le coût de production de la <span class="maj">ps</span>5 en dessous des 400 dollars comme ce fut le cas avec la <span class="maj">ps</span>4. L'utilisation massive de mémoire flash (<span class="maj">ram</span>, <span class="maj">ssd</span>) ainsi que d'un système de dissipation thermique amélioré engendrant un phénomène de surcoût, Bloomberg avance ainsi un coût de production unitaire de la <span class="maj">ps</span>5 autour de 450 dollars. Toujours selon ce même journal, le prix de vente de la console serait en voie d'être finalisé et un débat subsisterait au sein de la firme : vendre la console à perte pour concurrencer Microsoft ou bien devenir rentable dès la sortie de la machine. Malgré l'épidémie du coronavirus, il semblerait que cela n'ait pas eu encore d'incidence sur les préparatifs de la production de la console.

            Bloomberg annonce également qu'un nouveau casque de réalité virtuelle pour la console est en préparation et que sa sortie serait prévue après le lancement de la <span class="maj">ps</span>5.</p>
      </section>
    </main>
  </body>
</html>
