<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="../css/style.css">
    <title><?= $title ?></title>
  </head>
  <body class="body--sonyindex">
    <section class="bloc--sonyindex">
      <article class="bloc--sony bloc--present">
        <h1 class="title--present"><a href="https://fr.wikipedia.org/wiki/Sony" class="link--present decoration">Présentation</a></h1>
        </article>
        <article class="bloc--sony bloc--consoles">
          <h1 class="title--consoles"><a href="consoles-index.php" class="decoration link--consoles">Consoles</a></h1>
        </article>
      </section>
    </body>
    </html>
